"""Regenerate app/static/icons.js from a pinned Lucide release.

Lucide (https://lucide.dev) is ISC licensed, so the icon geometry can be vendored
into this repository and served from the local FastAPI app. The dashboard is
installed on isolated plant networks, so nothing is fetched from a CDN at runtime.

Usage:
    python scripts/build_icons.py
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

LUCIDE_VERSION = "0.469.0"
SOURCE = f"https://unpkg.com/lucide-static@{LUCIDE_VERSION}/icons"

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "app" / "static" / "icons.js"

# Every icon the dashboard asks for. Keep this list in sync with the data-icon
# attributes in index.html and the icon() calls in app.js; tests/test_core.py
# fails if a name is used without being generated here.
ICONS = (
    # navigation and shell
    "layout-dashboard",
    "settings",
    "tv",
    "menu",
    "x",
    "lock",
    "log-in",
    "log-out",
    "refresh-cw",
    "chevron-down",
    "chevron-up",
    "chevron-left",
    "chevron-right",
    "arrow-right",
    # plant structure
    "factory",
    "layers",
    "plus",
    "pencil",
    "crop",
    "trash-2",
    "save",
    "tag",
    # machine card
    "cpu",
    "wifi",
    "wifi-off",
    "power",
    "play",
    "pause",
    "skip-back",
    "skip-forward",
    "shield-check",
    "triangle-alert",
    "gauge",
    "trending-up",
    "list",
    "clock",
    "circle-check",
    "circle-x",
    "circle-help",
    # status and footer
    "info",
    "inbox",
    "server",
    "github",
    "instagram",
    "link",
)

INNER = re.compile(r"<svg[^>]*>(.*)</svg>", re.DOTALL)


def fetch(name: str) -> str:
    with urllib.request.urlopen(f"{SOURCE}/{name}.svg", timeout=20) as response:
        return response.read().decode("utf-8")


def body(name: str) -> str:
    match = INNER.search(fetch(name))
    if not match:
        raise SystemExit(f"unexpected SVG payload for {name!r}")
    return " ".join(match.group(1).split())


HEADER = f'''// Generated by scripts/build_icons.py - do not edit by hand.
//
// Icons from Lucide {LUCIDE_VERSION} (https://lucide.dev), ISC licensed.
// Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part
// of Feather Icons (MIT), and by Lucide Contributors 2022. Full licence text:
// https://github.com/lucide-icons/lucide/blob/main/LICENSE
//
// The geometry is vendored so the dashboard works on networks without internet.
'''


def main() -> int:
    entries = []
    for name in ICONS:
        entries.append(f'  {json.dumps(name)}: {json.dumps(body(name))},')
    payload = (
        HEADER
        + '''
// Lucide geometry is stroke based, so the size comes from CSS and the colour from
// the inherited text colour.
const ICON_ATTRS = {
  viewBox: '0 0 24 24',
  fill: 'none',
  stroke: 'currentColor',
  'stroke-width': '2',
  'stroke-linecap': 'round',
  'stroke-linejoin': 'round',
  'aria-hidden': 'true',
};

const ICONS = {
'''
        + "\n".join(entries)
        + """
};

function svgMarkup(name, extraClass) {
  const body = ICONS[name];
  if (!body) return '';
  const className = extraClass ? `icon ${extraClass}` : 'icon';
  const attributes = Object.entries(ICON_ATTRS)
    .map(function (entry) { return `${entry[0]}="${entry[1]}"`; })
    .join(' ');
  return `<svg class="${className}" ${attributes}>${body}</svg>`;
}

function icon(name, extraClass) {
  return svgMarkup(name, extraClass);
}

// Static markup keeps an empty <svg data-icon="..."> placeholder so index.html
// stays readable; the placeholder is filled in and stops matching afterwards.
function hydrateIcons(root) {
  (root || document).querySelectorAll('svg[data-icon]').forEach(function (node) {
    const body = ICONS[node.dataset.icon];
    if (!body) return;
    node.classList.add('icon');
    Object.entries(ICON_ATTRS).forEach(function (entry) { node.setAttribute(entry[0], entry[1]); });
    node.innerHTML = body;
    node.removeAttribute('data-icon');
  });
}
"""
    )
    TARGET.write_text(payload, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} with {len(ICONS)} icons")
    return 0


if __name__ == "__main__":
    sys.exit(main())
